name: Linky
description: New Sync Energy dashboards with your Linky smart meter
version: 1.42e
slug: linky
init: false
url: https://github.com/aigle1234/test-linky.git
#image: ghcr.io/aigle1234/ha-linky-{arch}
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
homeassistant_api: true
hassio_api: true
map:
  - addon_config
options:
  meters:
    - prm: ''
      token: ''
      name: 'Linky consumption'
      action: 'sync'
      production: false
    - prm: ''
      token: ''
      name: 'Linky production'
      action: 'sync'
      production: true
schema:
  meters:
    - prm: str?
      token: str?
      name: str?
      action: list(sync|reset)
      production: bool?
